on:
  push:
    branches:
      - main
      - develop

env:
  BUILD_VERSION: 3.1.0.${{github.run_number}}

jobs:
  build:
    runs-on: windows-latest
    env:
      APP_INSIGHTS_INSTRUMENTATION_KEY: ${{secrets.APP_INSIGHTS_INSTRUMENTATION_KEY}}
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Restore source
        run: |
          dotnet restore source/server/Karamem0.Preddy.sln
      - name: Build web
        run: |
          dotnet publish source/server/Karamem0.Preddy.Web/Karamem0.Preddy.Web.csproj `
            -c Release `
            -o artifact/web `
            -p:Version=${{env.BUILD_VERSION}} `
            -p:FileVersion=${{env.BUILD_VERSION}}
      - name: Upload web build files
        uses: actions/upload-artifact@v3
        with:
          name: preddy-web
          path: artifact/web
      - name: Build functions
        run: |
          dotnet publish source/server/Karamem0.Preddy.Functions/Karamem0.Preddy.Functions.csproj `
            -c Release `
            -o artifact/func `
            -p:Version=${{env.BUILD_VERSION}} `
            -p:FileVersion=${{env.BUILD_VERSION}}
      - name: Upload functions build files
        uses: actions/upload-artifact@v3
        with:
          name: preddy-func
          path: artifact/func
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Connect to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Download web build files
        uses: actions/download-artifact@v3
        with:
          name: preddy-web
          path: artifact/web
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.APP_WEB_NAME}}
          package: artifact/web
      - name: Download functions  build files
        uses: actions/download-artifact@v3
        with:
          name: preddy-func
          path: artifact/func
      - name: Deploy to Azure Functions
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.APP_FUNC_NAME}}
          package: artifact/func
